project:
  type: website

website:
  title: "Aidan Ohlson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: education.qmd
        text: Experience
      - href: contact.qmd
        text: Contact Me

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto