---
title: "Projects"
---

Here are a few projects I've completed that explore different areas of data 
science, statistical analysis, and machine learning techniques. I'm continuing 
to build and expand this portfolio as I go!




#### Dynamics of Content, Sentiment, and Theme in the Presidency

This project used text mining and machine learning to analyze U.S. presidential 
speeches. After preprocessing the text, I applied sentiment analysis 
(NRC lexicon), topic modeling (LDA), and word frequency analysis to explore 
potential patterns across eras and parties. I also built predictive models 
(SVM and Random Forest) to classify speeches by era and party.

[Presentation](133_project_slides.pdf){target="_blank"}

[Full Report](405815712_stats133_finalProject.pdf){target="_blank"}





#### Trump’s Twitter: Shifts Through Time and Context

This project analyzes over a decade of tweets from Donald Trump. After mining 
and preprocessing the tweet text, I applied sentiment analysis and Latent 
Dirichlet Allocation (LDA) to identify thematic topics across tweets and 
explored how these topics and sentiments correlated with user engagement. 
Finally, I built a multiple linear regression model to predict likes based on 
sentiment scores and topic categories, revealing how tone and content affected
public response.

[Presentation](Trump_Twitter_slides.pdf){target="_blank"}

[Full Report](Trump_Twitter_report.pdf){target="_blank"}





#### Predicting NBA Game Outcomes Using Supervised Learning Methods

This project builds predictive models to classify NBA game outcomes using 
engineered features from team statistics, home/away context, and rest days.
After cleaning and transforming the dataset, both Random Forest and Support 
Vector Machine models were trained using 10-fold cross-validation. Feature 
importance was analyzed, and time-decay weighting was tuned to improve 
performance.

[Code and Modeling Results](modified_stats101c_final_project.pdf){target="_blank"}





#### This Website (GitHub Repo)

This website was built in RStudio using Quarto. After creating and rendering the 
site locally, the project was tracked with Git and pushed to a GitHub repository 
using Bash commands. The GitHub repository was then connected to Netlify, which 
automatically builds and deploys the website whenever changes are pushed to 
GitHub. This is a fun project to keep updating and improving over time. 

[Website Repository](https://github.com/aidanohlson/aidan-ohlson-site){target="_blank"}